[package]
name = "lootbaggerd"
version = "0.1.0"
authors = ["Ferocity <christian.fries123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "../core" }
log = "0.4"
simple_logger = "1.11.0"